---
title: "Jacob's Stuff"
author: "Jacob Kresnicka"
date: "11/20/2019"
output: html_document
---

```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```


```{r}

Spotify_Top_2017 <- read_csv("Spotify/Spotify Top 2017.csv")
Spotify_Top_2018 <- read_csv("Spotify/Spotify Top 2018.csv")
Spotify_Big <- read_csv("SpotifyFeatures.csv")

Spotify_Master<-Spotify_Top_2017 %>% 
  bind_rows(Spotify_Top_2018)
```

```{r}
Spotify_Big %>%
  group_by(genre) %>%
  summarize(averagedanceability = mean(danceability)) %>%
  arrange(desc(averagedanceability)) %>%
  ggplot(aes(x=fct_reorder(genre,averagedanceability,mean),
             y=averagedanceability)) +
  geom_col(color = "black", fill = "green") +
  coord_flip() +
  theme_minimal() +
  labs(x="Genre of Music", y = "Average Dancibility Ratings",
       title = "Average Dancibility Ratings For Genre")
```

```{r}
Spotify_Big %>%
  group_by(genre) %>%
  summarize(averagepopularity = mean(popularity)) %>%
  arrange(desc(averagepopularity)) %>%
  ggplot(aes(x=fct_reorder(genre,averagepopularity,mean),
             y=averagepopularity)) +
  geom_col(color = "black", fill = "green") +
  coord_flip() +
  theme_minimal() +
  labs(x="Genre of Music", y = "Average Popularity",
       title = "Average Popularity For Genre")
```

