---
title: "Wills's Stuff"
author: "Wills Hawley"
date: "11/12/2019"
output: html_document
---
```{r}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

```{r}
Spotify_Top_2017 <- read_csv("Spotify/Spotify Top 2017.csv")
Spotify_Top_2018 <- read_csv("Spotify/Spotify Top 2018.csv")
Spotify_Big <- read_csv("SpotifyFeatures.csv")

Spotify_Master<-Spotify_Top_2017 %>% 
  bind_rows(Spotify_Top_2018)
```
What makes a hit song?

##### Would it be worth comparing 2017 v. 2018 songs as well for our analysis?
```{r}
Spotify_Master %>% 
  ggplot() +
  geom_histogram(aes(x=tempo),binwidth=12)
```
```{r}
Spotify_Master %>% 
  ggplot() +
  geom_histogram(aes(x=key),binwidth=1) +
  labs(y="keys",title="Master")
Spotify_Top_2017 %>% 
  ggplot() +
  geom_histogram(aes(x=key),binwidth=1) +
  labs(x="Musical Key",title=2017) +
  theme_minimal()
Spotify_Top_2018 %>% 
  ggplot() +
  geom_histogram(aes(x=key),binwidth=1) +
  labs(x="Key",title=2018) +
  theme_minimal()
```
```{r}
Artist_Count<-Spotify_Master %>% 
  group_by(artists) %>% 
  count() %>% 
  arrange(desc(n))
Artist_Count %>% 
  ggplot() +
  geom_histogram(aes(x=n),binwidth=1) +
  theme_minimal() +
  labs(x="Number of Top 100 Songs 2017-2018 by Artist",y="Count")
Artist_Count %>% 
  top_n(10)
```
```{r}
Spotify_Big %>% 
  ggplot() +
  geom_histogram(aes(x=tempo),binwidth=12)
```
```{r}
Spotify_Big %>% 
  ggplot() +
  geom_histogram(aes(x=loudness))
Spotify_Master %>% 
  ggplot() +
  geom_histogram(aes(x=loudness))
```
```{r}
Spotify_Big %>% 
  ggplot() +
  geom_histogram(aes(x=liveness))
Spotify_Master %>% 
  ggplot() +
  geom_histogram(aes(x=liveness))
```
```{r}
Spotify_Big %>% 
  group_by(genre) %>% 
  summarize(avg_speechiness=mean(speechiness)) %>% 
  arrange(avg_speechiness)
```
```{r}
Spotify_Big %>% 
  filter(genre=="Anime") %>% 
  ggplot() +
  geom_histogram(aes(x=valence),binwidth=.03)
Spotify_Big %>% 
  filter(genre=="World") %>% 
  ggplot() +
  geom_histogram(aes(x=valence),binwidth=.03)
Spotify_Big %>% 
  filter(genre=="Rock") %>% 
  ggplot() +
  geom_histogram(aes(x=valence),binwidth=.03)
Spotify_Big %>% 
  filter(genre=="Soul") %>% 
  ggplot() +
  geom_histogram(aes(x=valence),binwidth=.03)
```

```{r,fig.width=9,fig.height=5}
Spotify_Big %>% 
  filter(genre=="Anime") %>% 
  ggplot() +
  geom_hex(aes(x=valence,y=popularity)) +
  labs(title="Anime") +
  theme_minimal()
Spotify_Big %>% 
  filter(genre=="R&B") %>% 
  ggplot() +
  geom_hex(aes(x=valence,y=popularity)) +
  labs(title="R&B") +
  theme_minimal()
```
```{r,fig.width=7,fig.height=5}
Spotify_Big %>% 
  filter(genre=="Alternative") %>% 
  ggplot() +
  geom_hex(aes(x=valence,y=popularity)) +
  labs(title="Alternative") +
  theme_minimal() 
```
```{r,fig.width=10}
Spotify_Big %>% 
  ggplot() +
  geom_histogram(aes(x=valence),binwidth=0.1) +
  facet_wrap(~genre) +
  theme_minimal() +
  labs(x="Valence",y="Count",title="Distribution of Valence by genre")
```
```{r,echo=FALSE,fig.width=10}
Spotify_Big %>% 
  ggplot() +
  geom_histogram(aes(x=energy),binwidth=0.1) +
  facet_wrap(~genre) +
  theme_minimal() +
  labs(x="Valence",y="Count",title="Distribution of Valence by genre")
```
```{r,fig.width=10}
Spotify_Big %>% 
  ggplot() +
  geom_hex(aes(x=energy,y=popularity)) +
  facet_wrap(~genre) +
  theme_minimal()
```
 
*** Look at Opera, Hip-Hop, Ska, Soundtrack, Classical
 
 
```{r,fig.width=10}
Spotify_Big %>% 
  ggplot() +
  geom_hex(aes(x=tempo,y=popularity)) +
  facet_wrap(~genre) +
  theme_minimal()
```

*** Look at Children's music, Comedy, Reggaeton, Soundtrack, Jazz, 

```{r,fig.width=10}
Spotify_Big %>% 
  ggplot() +
  geom_hex(aes(x=liveness,y=popularity)) +
  facet_wrap(~genre) +
  theme_minimal()
```


```{r}
Mean_Variables<-Spotify_Big %>% 
  group_by(genre) %>% 
  summarize(avg_popularity=mean(popularity),
            avg_acousticness=mean(acousticness),
            avg_danceability=mean(danceability),
            avg_duration=mean(duration_ms),
            avg_energy=mean(energy),
            avg_instrumentalness=mean(instrumentalness),
            avg_liveness=mean(liveness),
            avg_loudness=mean(loudness),
            avg_speechiness=mean(speechiness),
            avg_tempo=mean(tempo),
            avg_valence=mean(valence))
Mean_Variables
```

```{r,fig.width=18}
Spotify_Big %>% 
  ggplot() +
  geom_boxplot(aes(x=genre,y=popularity))
```

```{r,fig.height=8}
Spotify_Big %>% 
  ggplot() +
  geom_boxplot(aes(x=fct_reorder(genre,.x=danceability,.fun=median),
                   y=danceability,fill=genre)) +
  coord_flip() +
  labs(x="Genre",y="Danceability") +
  theme_minimal()
```
```{r,fig.width=18}
Spotify_Big %>% 
  ggplot() +
  geom_boxplot(aes(x=genre,y=duration_ms))
```
```{r}
Spotify_Big %>%
  ggplot() +
  geom_jitter(aes(x=danceability,y=popularity)) +
  geom_smooth(aes(x=danceability,y=popularity),method=lm,color="red") +
  facet_wrap(~genre)
```

